Add type attribute, mobile IE11 stabilisation
Financial-Times/o-video pull request #20
Opened 2016-08-05 09:54 UTC by debugwand

https://jira.ft.com/browse/NFT-550 reports video failing on mobile windows IE11 and edge, I have found to work but be flaky.

Grey box is present for a long time (probably speed issue) and a decode error will sometimes be thrown.

This adds 'type' to the video element in the _hope_ that it gives enough assistance to the user agent to improve stability.

2016-08-10 16:34 UTC, AlbertoElias commented
This looks good, but would it be possible to check if it fixes it or not before merging?

2016-09-06 15:54 UTC, JakeChampion commented
@debugwand Did your patch fix the issue?

2016-09-27 16:14 UTC, JakeChampion requested changes
This branch now has conflicts with master.

2016-10-04 15:00 UTC, JakeChampion commented
@debugwand Shall we assume this work is no longer required?

2016-10-14 14:44 UTC, JakeChampion commented
Closing the PR, feel free to re-open if it is needed.

2016-10-14 17:19 UTC, closed without merging