Ads loading messaging
Financial-Times/o-video pull request #54
Opened 2016-09-27 15:11 UTC by i-like-robots

This adds a loading indicator when ads are enabled to provide immediate feedback to the user when they click an o-video element. 

** do not merge, needs more testing**

![loader](https://cloud.githubusercontent.com/assets/271645/18879617/e8452442-84cc-11e6-8986-1095f6c67729.gif)

2016-09-27 16:18 UTC, JakeChampion requested changes
This branch has conflicts with the latest version of o-video.

2016-09-28 15:09 UTC, i-like-robots commented
I think this is ready for review... will continue testing on devices

2016-09-28 16:58 UTC, JakeChampion commented
@rowanbeentje would you be able to get the web-app QA team to test this PR out at all?

2016-09-28 18:12 UTC, rowanbeentje commented
Sure, let me pull it into master and ask...

2016-09-29 11:23 UTC, rowanbeentje commented
OK, feedback from the apps qa team...

1. On iOS, a vertical bar one pixel wide of the video shows peeking out to the left of the o-video__loading-state/o-video__ad overlay.  This seems to be because o-video__ad is display: table, and o-video__loading-state is display: table-cell but there's also an absolute div in there.  This isn't so noticeable unless the video has a bright background.
2. The loading spinner always seems to display for a fixed period of time (and the code backs this up - always shows for a fixed 2s?)  So on a slow connection, the spinner shows, then hides, then multiple seconds later the advert plays.  Not sure if this is intended or if it was supposed to be hooked up to the ad play event with a minimum of 2s display.

Otherwise all good...

2016-09-29 11:37 UTC, i-like-robots commented
Thanks @rowanbeentje 

1. I'll add some styles to cover this issue
2. I'll hook the spinner up to removed when the ad is ready to play rather than after the arbitrary time

2016-09-29 15:34 UTC, rowanbeentje commented
These both look good to me!  (Haven't passed it back to QA but gave it a quick try locally)

2016-09-30 14:13 UTC, JakeChampion approved these changes

2016-09-30 14:50 UTC, merged